default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: <%= Rails.application.credentials.dig(:postgres, :user) %>
  password: <%= Rails.application.credentials.dig(:postgres, :password) %>

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  url: <%= Rails.application.credentials.dig(:postgres, :url) %>